### ISSUE TITLE
formatter is undefined in getSubscribers

### ISSUE THREAD

**Issue by ephelip** [justmiles/hubot-gerrit#1]
The following error appears when getSuscribers is called with an adaptater different from slack

[Mon Aug 29 2016 16:16:34 GMT-0400 (EDT)] ERROR TypeError: Cannot read property 'events' of undefined
  at Socket.<anonymous> (/home/hubot/nono/node_modules/hubot-gerrit/src/gerrit.coffee:307:7, <js>:450:30)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:531:20)

**Comment by justmiles** [comment]
Fixed in #3.
