### ISSUE TITLE
robotRooms is undefined

### ISSUE THREAD

**Issue by ephelip** [justmiles/hubot-gerrit#2]
[Mon Aug 29 2016 08:40:03 GMT-0400 (EDT)] ERROR ReferenceError: robotRooms is not defined
  at /home/hubot/nono/node_modules/hubot-gerrit/src/gerrit.coffee:326:11, <js>:480:23
  at Socket.<anonymous> (/home/hubot/nono/node_modules/hubot-gerrit/src/gerrit.coffee:320:9, <js>:489:15)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:531:20)

**Comment by justmiles** [comment]
Fixed in #3.
